<div class="lightbox-backgrond" onclick="Wo_CloseLightbox();"></div>
<div class="lightbox-content multi">
	<button type="button" class="close" onclick="Wo_CloseLightbox();" style="color: #fff;opacity: 0.8;font-size: 28px;margin-left: 10px;position: absolute;right: 10px;text-shadow: 0 1px 2px #555;">
		<i class="zmdi zmdi-close"></i>
	</button>
	
<?php if (Wo_IsPostOnwer($wo['image']['post_id'], $wo['user']['user_id']) === true) : ?>
	<span onclick='Wo_RemoveLightboxAlbumImage(<?php echo $wo['image']['post_id'];?>,<?php echo $wo['image']['id'];?>);' class='pointer' style="color: #fff;opacity: 0.8;font-size: 22px;position: absolute;left: 10px;text-shadow: 0 1px 2px #555;">
		<i class="zmdi zmdi-delete"></i>
	</span>
<?php endif; ?>
	
	<div class="story-img">
		<img src="<?php echo $wo['image']['image_org'];?>" alt="media" class="album-mobi-img">
		<span class="changer previous-btn" onclick="Wo_PreviousAlbumPicture(<?php echo $wo['image']['post_id'];?>, <?php echo $wo['image']['id'];?>);">
			<i class="zmdi zmdi-chevron-left"></i>
		</span>
		<span class="changer next-btn multi" onclick="Wo_NextAlbumPicture(<?php echo $wo['image']['post_id'];?>, <?php echo $wo['image']['id'];?>);">
			<i class="zmdi zmdi-chevron-right"></i>
		</span>
		<a class="changer album-img-dwn" href="<?php echo $wo['image']['image_org'];?>" download style="left: 50%;transform: translate(-50%,20%);top: auto;bottom: 20%;width: 41px;"><i class="zmdi zmdi-download" style="font-size:22px"></i></a>
	</div>
</div>
<script>
$(document).keydown(function(e) {
    if (e.keyCode == 27) {
        Wo_CloseLightbox();
    }   
});
$( ".story-img" ).mouseover(function() {
  $( ".changer" ).fadeIn(200);
});
$( ".story-img" ).mouseleave(function() {
  $( ".changer" ).fadeOut(200);
});
</script>