<div class="lightbox-backgrond" onclick="Wo_CloseLightbox();"></div>
<div class="lightbox-content multi">
	<button type="button" class="close" onclick="Wo_CloseLightbox();" style="color: #fff;opacity: 0.8;font-size: 28px;text-shadow: none;margin-left: 10px;position: absolute;right: 10px;">
		<i class="zmdi zmdi-close"></i>
	</button>
	<div class="story-img">
		<img src="<?php echo $wo['image']['image_org'];?>" alt="media" class="album-mobi-img">
		<span class="changer previous-btn" onclick="Wo_PreviousProductPicture(<?php echo $wo['image']['product_id'];?>, <?php echo $wo['image']['id'];?>);">
			<i class="zmdi zmdi-chevron-left"></i>
		</span>
		<span class="changer next-btn multi" onclick="Wo_NextProductPicture(<?php echo $wo['image']['product_id'];?>, <?php echo $wo['image']['id'];?>);">
			<i class="zmdi zmdi-chevron-right"></i>
		</span>
	</div>
</div>
<script>
$(document).keydown(function(e) {
    if (e.keyCode == 27) {
        Wo_CloseLightbox();
    }   
});
$(document).keydown(function(e) {
    if (e.keyCode == 27) {
        Wo_CloseLightbox();
    }   
});
$( ".story-img" ).mouseover(function() {
  $( ".changer" ).fadeIn(200);
});
$( ".story-img" ).mouseleave(function() {
  $( ".changer" ).fadeOut(200);
});
</script>
