<div class="sidebar-conatnier">
   
   <ul class="list-group filterby settings-by">
      <li class="list-group-item hidden" contenteditable="false">Settings</li>
      <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'general-setting') ? 'avtive': '';?>"><a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' . $wo['setting']['page_name'] . '&link3=general-setting');?>" data-ajax="?link1=page-setting&page=<?php echo $wo['setting']['page_name'];?>&link3=general-setting"><?php echo $wo['lang']['general'];?></a></li>
      <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'profile-setting') ? 'avtive': '';?>"><a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' . $wo['setting']['page_name'] . '&link3=profile-setting');?>" data-ajax="?link1=page-setting&page=<?php echo $wo['setting']['page_name'];?>&link3=profile-setting"><?php echo $wo['lang']['page_information'];?></a></li>
      <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'social-links') ? 'avtive': '';?>"><a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' . $wo['setting']['page_name'] . '&link3=social-links');?>" data-ajax="?link1=page-setting&page=<?php echo $wo['setting']['page_name'];?>&link3=social-links"><?php echo $wo['lang']['social_links'];?></a></li>
      <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'avatar-setting') ? 'avtive': '';?>"><a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' . $wo['setting']['page_name'] . '&link3=avatar-setting');?>" data-ajax="?link1=page-setting&page=<?php echo $wo['setting']['page_name'];?>&link3=avatar-setting"><?php echo $wo['lang']['avatar_and_cover'];?></a></li>

      <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'design-setting') ? 'avtive': '';?>"><a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' . $wo['setting']['page_name'] . '&link3=design-setting');?>" data-ajax="?link1=page-setting&page=<?php echo $wo['setting']['page_name'];?>&link3=design-setting"><?php echo $wo['lang']['design'];?></a></li>

      <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'admins') ? 'avtive': '';?>"><a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' . $wo['setting']['page_name'] . '&link3=admins');?>" data-ajax="?link1=page-setting&page=<?php echo $wo['setting']['page_name'];?>&link3=admins"><?php echo $wo['lang']['admin'];?></a></li>

      <li class="list-group-item filter-by-li <?php echo ($wo['setting_page'] == 'delete-page') ? 'avtive': '';?>"><a href="<?php echo Wo_SeoLink('index.php?link1=page-setting&page=' . $wo['setting']['page_name'] . '&link3=delete-page');?>" data-ajax="?link1=page-setting&page=<?php echo $wo['setting']['page_name'];?>&link3=delete-page"><?php echo $wo['lang']['delete_page'];?></a></li>
   </ul>
   <?php echo Wo_LoadPage('footer/sidebar-footer')?>
</div>
</div>