<div class="posts-container list-group">
	<div class="side-widget-name">
		<?php echo $wo['lang']['welcome_to_news_feed'];?>
	</div>
	<div class="no-posts" style="margin-top: 0px;">
		<h1>
			<span class="zmdi-hc-stack zmdi-hc-lg" style="-webkit-filter: drop-shadow(0px 9px 7px #8BC34A82);filter: drop-shadow(0px 9px 7px #8BC34A82);">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #8BC34A;"></i>
				<i class="zmdi zmdi-edit zmdi-hc-stack-1x zmdi-hc-inverse"></i>
			</span>
		</h1>
		<?php echo $wo['lang']['say_hello'];?>
	</div>
</div>

<?php $users = Wo_UserSug(7); if (count($users) != 0) ?>
<ul class="list-group" id="sidebar-user-list-container" style="padding: 0px 10px;">
	<li class="list-group-item text-muted side-widget-name" contenteditable="false">
		<?php echo $wo['lang']['people_you_may_know'];?>
	</li>
	<li>
		<div class="sidebar-users-may-know-container">
			<?php 
			foreach ($users as $wo['UsersList']) {
			$wo['UsersList']['user_name'] = mb_substr($wo['UsersList']['name'],0,10, "utf-8");
			echo Wo_LoadPage('header/user-list');
			} 
			?>
		</div>
		<div class="clear"></div>
	</li>
</ul>