<?php if ($wo['loggedin'] == true) { ?>
<div class="left-sidebar">
<div class="sidebar-conatnier">
<div class="home profile-style main sidebar-profile-style">
            <div class="card hovercard" style="border-radius: 0px;">
                <div class="cardheader">
                    <img src="<?php echo $wo['user']['cover']?>" id="cover-image" alt="<?php echo $wo['user']['name']?> Cover Image">
                </div>
                <div class="avatar">
                    <img id="updateImage-<?php echo $wo['user']['user_id']?>" alt="<?php echo $wo['user']['name']?> Profile Picture" src="<?php echo $wo['user']['avatar']?>">
                </div>
                <div class="info">
                    <div class="title">
                        <a id="user-full-name" href="<?php echo $wo['user']['url'];?>"><?php echo $wo['user']['name']?></a>
                        <?php if($wo['user']['verified'] == 1):?>
                        <i class="fa fa-check-circle verified-color" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"></i>
                        <?php endif;?>
                    </div>
					<div class="infolinkz" style="display: inline-block;margin-left: 65px;top: -17px;position: inherit;">
						<a href="<?php echo Wo_SeoLink('index.php?link1=messages'); ?>" data-toggle="tooltip" title="<?php echo $wo['lang']['messages'];?>" style="color: #2196F3;"><i class="zmdi zmdi-comment-text-alt"></i></a>
						<a href="<?php echo Wo_SeoLink('index.php?link1=setting'); ?>" data-toggle="tooltip" title="<?php echo $wo['lang']['setting'];?>" style="color: #4CAF50;"><i class="zmdi zmdi-settings"></i></a>
					</div>
                </div>
            </div>
        </div>
</div>
	<ul>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=search?query='); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #8BC34A;"></i>
					<i class="zmdi zmdi-widgets zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['explore'];?>
			</a>
		</li>
		
		<?php if ($wo['config']['find_friends'] == 1) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #b2c17c;"></i>
					<i class="zmdi zmdi-pin zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['find_friends'];?>
			</a>
		</li>
		<?php } ?>
		
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=saved-posts');?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #fac539;"></i>
					<i class="zmdi zmdi-bookmark-outline zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['saved_posts'];?>
			</a>
		</li>
		
		<?php if ($wo['config']['groups'] == 1) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=groups'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #03A9F4;"></i>
					<i class="zmdi zmdi-group-work zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['my_groups'];?>
			</a>
		</li>
		<?php } ?>
		
		<?php if ($wo['config']['pages'] == 1) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f79f58;"></i>
					<i class="zmdi zmdi-google-pages zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['my_pages'];?>
			</a>
		</li>
		<?php } ?>
		
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #b2c17c;"></i>
					<i class="zmdi zmdi-collection-image zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['my_albums'];?>
			</a>
		</li>
		
		<?php if ($wo['config']['blogs'] == 1) { ?>
		<li><hr></li>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=blogs'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f35d4d;"></i>
					<i class="zmdi zmdi-blogger zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['blog'] ?>
			</a>
		</li>
		<?php } ?>
		
		<?php if (Wo_CanBlog() == true) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=my-blogs'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #009da0;"></i>
					<i class="zmdi zmdi-receipt zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['my_articles'] ?>
			</a>
		</li>
		<?php } ?>
		
		<?php if ($wo['config']['classified'] == 1) { ?>
		<li><hr></li>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=products'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #6eceba;"></i>
					<i class="zmdi zmdi-store zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['market'];?>
			</a>
		</li>
		<?php } ?>
		
		<?php if ($wo['config']['classified'] == 1) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=my-products'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #6a7f9a;"></i>
					<i class="zmdi zmdi-shopping-cart zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['my_products'];?>
			</a>
		</li>
		<?php } ?>
		
        <li><hr></li>
		
		<?php if ($wo['config']['games'] == 1) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=new-game'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #03A9F4;"></i>
					<i class="zmdi zmdi-gamepad zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['games'];?>
			</a>
		</li>
		<?php } ?>
        
		<?php if ($wo['config']['forum'] == 1) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=forum'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #fac539;"></i>
					<i class="zmdi zmdi-comments zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['forum'];?>
			</a>
		</li>
		<?php } ?>
		
		<?php if ($wo['config']['events'] == 1) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=events'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f25e4e;"></i>
					<i class="zmdi zmdi-calendar zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['events'] ?>
			</a>
		</li>
		<?php } ?>
		
		<?php if ($wo['config']['movies'] == 1) { ?>
		<li>
			<a class="wabe" href="<?php echo Wo_SeoLink('index.php?link1=movies'); ?>">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #8d73cc;"></i>
					<i class="zmdi zmdi-movie-alt zmdi-hc-stack-1x zmdi-hc-inverse"></i>
				</span>
				<?php echo $wo['lang']['movies'];?>
			</a>
		</li>
		<?php } ?>
		
	</ul>
</div>
<?php } ?>