<span id="going-<?php echo $wo['event']['id']?>">
    <button type="button" onclick="Wo_RegisterEventGoing(<?php echo $wo['going']['id'];?>)" class="mdbtn wabe btn btn-success btn-sm" style="font-size: 14px;margin-bottom: 10px;font-weight: bold;">
       <i class="zmdi zmdi-calendar" style="font-size: 20px;margin: -1px 5px 0px 0px;"></i>
       <span class="button-text"> <?php echo $wo['lang']['go'];?></span>
    </button>
</span>