<span id="interested-<?php echo $wo['interested']['id']?>">
    <button type="button" onclick="Wo_RegisterEventInterested(<?php echo $wo['interested']['id'];?>)" class="mdbtn btn btn-info btn-sm" style="font-size: 14px;font-weight: bold;">
       <i class="zmdi zmdi-star" style="font-size: 20px;margin: -1px 5px 0px 0px;"></i>
       <span class="button-text"> <?php echo $wo['lang']['interested'];?></span>
    </button>
</span>