<span id="going-<?php echo $wo['event']['id']?>">
    <button type="button" onclick="Wo_RegisterEventGoing(<?php echo $wo['going']['id'];?>)" class="mdbtn btn-active btn btn-default btn-sm" style="font-size: 14px;margin-bottom: 10px;font-weight: bold;height: 36px;">
       <i class="zmdi zmdi-check" style="font-size: 20px;margin: -1px 5px 0px 0px;"></i>
       <span class="button-text"> <?php echo $wo['lang']['going'];?></span>
    </button>
</span>