<?php
$notification_alert     = Wo_CountNotifications(array(
    'unread' => true,
    'data' => 'all'
));
$messages_alert         = Wo_CountMessages(array(
    'new' => true
));
$followers_alert        = Wo_CountFollowRequests();
$hidden_class           = '';
$messages_hidden_class  = '';
$followers_hidden_class = '';
$unread_update_notification = 'unread-update';
$unread_update_messages = 'unread-update';
$unread_update_followers = 'unread-update';
if ($notification_alert == 0) {
    $hidden_class = ' hidden';
    $unread_update_notification = '';
}
if ($messages_alert == 0) {
    $messages_hidden_class = ' hidden';
    $unread_update_messages = '';
}
if ($followers_alert == 0) {
    $followers_hidden_class = ' hidden';
    $unread_update_followers = '';
}
?>

<ul class="nav navbar-nav navbar-right <?php echo Wo_RightToLeft('pull-right');?> equmobiwidthul">
	<li class="navbar-home equmobiwidth" id="mobihomiz">
		<a href="https://diadiemhaiduong.com" id="home-button" <?php echo ($wo['config']['smooth_loading'] == 0) ? 'onclick="Wo_ChangeHomeButtonIcon()"' : ''?>>
			<i class="zmdi zmdi-home" style="font-size: 19px;"></i>
			<div class="mobihide"><?php echo $wo['lang']['home']; ?></div>
		</a>
	</li>
				
	<li class="dropdown msearch-container equmobiwidth" style="display:none">
		<a href="#" class="dropdown-toggle sixteen-font-size" data-toggle="dropdown" role="button" aria-expanded="false" style="min-height: 50px;">
			<i class="zmdi zmdi-search" style="font-size: 22px;margin-top: -2px;"></i>
		</a>
		<ul class="dropdown-menu clearfix mobisearchcont" role="menu" style="height: 100vh;">
			<li class="dropdown search-container">
				<form class="navbar-form navbar-left col-lg-12 form-group" data-toggle="dropdown" role="button" id="navbar-searchbox" role="search" style="display: block;border: none;padding: 0px;margin: 10px 10px;">
					<input type="text" class="form-control search-input" onkeyup="Wo_DetectSearchType(this.value)" placeholder="<?php echo $wo['lang']['search_header_label']; ?>" dir="auto" <?php if ($wo['loggedin'] == true) { echo 'onfocus="Wo_GetRecentSearchs()"';}?> id="mobi-search-input" autofocus>
				</form>
				<ul class="dropdown-menu search-dropdown-container" style="display: block;" role="menu">
						<div class="search-dropdown-result">
							<?php
							if ($wo['loggedin'] == true) {
							foreach (Wo_GetRecentSerachs() as $wo['result']) {
							echo Wo_LoadPage('header/search');
							}
							}
							?>
						</div>
				</ul>
			</li>
		</ul>
	</li>
	   
	<li class="dropdown notification-container equmobiwidth"">
		<span class="new-update-alert<?php echo $hidden_class;?>">
			Bạn cần đăng nhập
		</span>
		<a href="#" class="dropdown-toggle <?php echo $unread_update_notification;?> sixteen-font-size" data-toggle="dropdown" role="button" aria-expanded="false" style="min-height: 50px;">
			<i class="zmdi zmdi-notifications" style="font-size: 22px;margin-top: -2px;"></i>
		</a>
		<ul class="dropdown-menu clearfix notifications-dropdown" role="menu">
			<li class="turn-off-sound <?php echo Wo_RightToLeft('text-left');?>">
				<span><a href ="https://diadiemhaiduong.com/welcome">Bạn cần đăng nhập để xem thông báo!</a></span> 
			</li>
		</ul>
	</li>
	<li class="dropdown requests-container equmobiwidth">
		<span class="new-update-alert<?php echo $followers_hidden_class;?>">
			Bạn cần đăng nhập
		</span>
		<a href="#" class="dropdown-toggle <?php echo $unread_update_followers;?> sixteen-font-size" data-toggle="dropdown" role="button" aria-expanded="false" style="min-height: 50px;">
			<i class="zmdi zmdi-shopping-cart-add" style="font-size: 22px;margin-top: -2px;"></i>
		</a>
		<ul class="dropdown-menu request-list clearfix notifications-dropdown" role="menu" style="padding: 0px;">
			<ul id="requests-list" style="padding-left: 0;padding: 10px;">
				<li>
					<span><a href ="https://diadiemhaiduong.com/welcome">Bạn cần đăng nhập để đăng bán!</a></span> 
				</li>
			</ul>
			
		</ul>
	</li>	
	<div class="topheadbar"></div>
<ul class="nav navbar-nav navbar-right <?php echo Wo_RightToLeft('pull-right');?>">
   <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
      <?php echo $wo['lang']['guest']; ?> 
      <span class="caret"></span>
      </a>
      <ul class="dropdown-menu" role="menu">
         <li>
            <a href="https://diadiemhaiduong.com/new-product">
           <i class="zmdi zmdi-google-pages" style="font-size: 16px;margin-right: 10px;"></i>
           Đăng bán miễn phí
            </a>
         </li>

         <li>
            <a href="https://diadiemhaiduong.com/welcome">
            <i class="fa fa-user" style="font-size: 16px;margin-right: 10px;"></i>
            <?php echo $wo['lang']['login']; ?>
            </a>
         </li>
         <li>
            <a href="<?php echo Wo_SeoLink('index.php?link1=register');?>">
            <i class="fa fa-sign-in" style="font-size: 16px;margin-right: 10px;"></i>
            <?php echo $wo['lang']['register']; ?>
            </a>
         </li>
      </ul>
   </li>
</ul>