<div class="page-margin">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h2 class="main text-center">
					<?php echo $wo['lang']['most_recent_art'] ?>
				</h2>
				<div class="clear"></div>
			</div>
			<?php if (Wo_CanBlog() == true) { ?>
			<div class="col-md-12 text-center">
				<a class="mdbtn btn btn-success" href="<?php echo Wo_SeoLink('index.php?link1=my-blogs'); ?>">
					<i class="zmdi zmdi-receipt zmdi-hc-fw"></i>
					<?php echo $wo['lang']['my_articles'] ?>
				</a>
			</div>
			<?php } ?>
		</div>
		
		<div class="offnavmenu">
			<div style="width: 100%;height: 33px;background: rgba(255, 221, 221, 0.55);">
				<span class="pull-left" style="font-weight: bold;color: #585858;font-size: 13px;padding: 7px;"><i class="zmdi zmdi-labels" style="color: #E91E63;font-size: 16px;margin-right: 4px;margin-top: -1px;"></i> <?php echo $wo['lang']['categories'] ?></span>
			</div>
			<ul class="list-group" style="border: 0px;margin-bottom: 40px;">
			    <?php 
			    $category_id = (!empty($_GET['id'])) ? (int) $_GET['id'] : 0;
			    foreach ($wo['page_categories'] as $key => $category) {
			    	$active = ($category_id == $key) ? ' active' : '';
			    ?>
					<li class="list-group-item gray-list<?php echo $active?>" style="font-weight: normal;border: 0px;border-bottom: 1px solid #ddd;"><a href="<?php echo Wo_SeoLink('index.php?link1=blog-category&id=' . $key) ?>" data-ajax="?link1=blog-category&id=<?php echo $key?>"><?php echo $category;?></a></li>
			    <?php } ?>
			</ul>
		</div>
		
		<div class="row">
			<div id="recent-blogs" class="fluid">
				<?php
						$pages = Wo_GetBlogs(array("limit" => 9));
			               
		                if (count($pages) > 0) {
		                    foreach ($pages as $key => $wo['article']){

		                    	$wo['article']['first'] = ($key == 0) ? true : false;
		                        echo Wo_LoadPage('blog/includes/card-list');

		                    }
		                } 

		                else {
		                   echo '<h5 class="search-filter-center-text"> ' . $wo['lang']['no_blogs_found'] . '</h5>';
		                }
		               
		         ?>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
			 	<div class="posts_load">
				    <?php if (count($pages) >= 9): ?>
					<div class="load-more">
	                    <button class="btn btn-default text-center pointer load-more-blogs" id="hren" >
	                    <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more_blogs'] ?></button>
	                </div>
	                <?php endif ?>
				</div>
			</div>
		</div>
	</div>
</div>

<style>
.float-fab{width: 45px;height: 45px;padding: 8px;position: absolute;right: 0px;margin-top: -40px;}
.ad-placement-header-footer {margin: auto;}
.float-fab i{margin: -1px 2px 0px 0px;font-size: 22px;}
#custblog{padding-left: 7px;padding-right: 7px;}
body {padding-left: 0px !important;}
.offnavmenu{display:none}
.navbar-default {padding-right: 0px;}

@media (min-width: 1024px){
.container {width: 900px;}
body {padding-left: 150px !important;padding-right: 0px !important;}
.navbar-default {padding-right: 45px;}
.offnavmenu{display:block;width: 180px;}
}

@media (min-width: 1200px){
body {padding-left: 0px !important;padding-right: 55px !important;}
.navbar-default {padding-right: 45px;}
.offnavmenu{display:block;width: 180px;}
}

@media (min-width: 1500px){
.container {width: 1000px;}
body {padding-left: 0px !important;padding-right: 60px !important;}
.navbar-default {padding-right: 60px;}
.offnavmenu {width: 230px;}
}

@media (max-width: 990px) {
body {padding-left: 0px !important;overflow-x: auto;}
}

@media (max-width: 500px) {
.blog-toggle-mobile{display:none}
}
</style>
<?php if($wo['loggedin'] == false) {  ?>
<style>
body {padding-left: 0px;}
.navbar-default {padding-right: 0px;}

@media (min-width: 1200px){
body {padding-left: 0px;padding-right: 0px;}
.navbar-default {padding-right: 0px;}
}
@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
.hideinmenu {display: none;}
}
</style>
<?php } ?>
<?php if($wo['language_type'] == 'rtl') { ?>
<style>
@media (min-width: 1024px){
body {padding-left: 200px !important;padding-right: 0px !important;}
}
@media (min-width: 1200px){
body {padding-left: 0px !important;padding-right: 0px !important;}
}
</style>
<?php } ?>

<script>
jQuery(document).ready(function($) {

	$('.blog-h-list').equalHeights();

    $(".load-more-blogs").click(function () {
  		var last_id = (($("div[data-blog-id]").length > 0) ? $("div[data-blog-id]:last").attr('data-blog-id') : 0);
		$.ajax({	  
		     url: Wo_Ajax_Requests_File(),
		     type: 'GET',
		     dataType: 'json',
		     data: {f:"load-recent-blogs",offset:last_id,total:9},
		     success:function(data){
		        if (data['status'] == 200) {
		            $("#recent-blogs").append(data['html']);
		            $('.blog-h-list').equalHeights();
		        }

		        else{
		           $(".posts_load").remove()
		        }
		     }
		});
	});
});

function ShareWindow(url, windowName) {
   newwindow = window.open('<?php echo $wo['config']['site_url']; ?>/sharer?url=' + url, windowName, 'height=600,width=800');
   if (window.focus) {
      newwindow.focus();
   }
   return false;
}
</script>