<div class="page-margin products">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12 text-center">
				<h3 class="main recent-articles">
					<?php echo $wo['lang']['most_recent_art'] ?>
				</h3>
				<div class="clear"></div>
			</div>
		</div>
		<div class="row">
			<div id="recent-blogs" class="fluid">
				<?php
						$pages = Wo_GetBlogs(array("limit" => 9));
			               
		                if (count($pages) > 0) {
		                    foreach ($pages as $key => $wo['article']){

		                    	$wo['article']['first'] = ($key == 0) ? true : false;
		                        echo Wo_LoadPage('blog/includes/card-list');

		                    }
		                } 

		                else {
		                   echo '<h5 class="search-filter-center-text"> ' . $wo['lang']['no_blogs_found'] . '</h5>';
		                }
		               
		         ?>
			</div>
		</div>

		<div class="row">
			<div class="col-md-12 col-lg-12 col-sm-12 col-sx-12">
			 	<div class="posts_load">
				    <?php if (count($pages) >= 9): ?>
					<div class="load-more">
	                    <button class="btn btn-default text-center pointer load-more-blogs" id="hren" >
	                    <i class="fa fa-arrow-down progress-icon" data-icon="arrow-down"></i> <?php echo $wo['lang']['load_more_blogs'] ?></button>
	                </div>
	                <?php endif ?>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
jQuery(document).ready(function($) {

	$('.blog-h-list').equalHeights();

    $(".load-more-blogs").click(function () {
  		var last_id = (($("div[data-blog-id]").length > 0) ? $("div[data-blog-id]:last").attr('data-blog-id') : 0);
		$.ajax({	  
		     url: Wo_Ajax_Requests_File(),
		     type: 'GET',
		     dataType: 'json',
		     data: {f:"load-recent-blogs",offset:last_id,total:9},
		     success:function(data){
		        if (data['status'] == 200) {
		            $("#recent-blogs").append(data['html']);
		            $('.blog-h-list').equalHeights();
		        }

		        else{
		           $(".posts_load").remove()
		        }
		     }
		});
	});
});
</script>

