<div id="welcomeheader">
<div class="container">
<div class="logo">
		<a href="<?php echo $wo['config']['site_url'];?>"><img src="<?php echo $wo['config']['theme_url'];?>/img/logouser.svg" alt="Logo"> </a>
	</div>
<div class="welcome-header">
   	<div class="absul-right">
   		<button class="mdbtn create-account" onclick="location.href='<?php echo $wo['config']['site_url'];?>';"><?php echo $wo['lang']['login']?></button>
   	</div>
   	<div class="clear"></div>
</div>
</div>
</div>