<?php $show_list = false;
	if ($wo['group_profile']['privacy'] == 1) {
		$show_list = true;
	} else if ($wo['group_profile']['privacy'] == 2) {
	if (!Wo_IsGroupOnwer($wo['group_profile']['id'])) {
		if (Wo_IsGroupJoined($wo['group_profile']['id'])) {
			$show_list = true;
		}
	} else {
		$show_list = true;
		}
	} 
?>
<div class="row page-margin" data-page="group" data-id="<?php echo $wo['group_profile']['id'];?>">
  <div class="profile-container">
     <div class="profile-top-line"></div>
      <div class="card hovercard">
        <div class="cardheader user-cover">
          <?php if(Wo_IsGroupOnwer($wo['group_profile']['id']) === true) { ?>
          <form action="#" method="post" class="profile-cover-changer">
            <div class="input-group">
              <span class="input-group-btn">
              <span class="btn btn-upload-image btn-file">
              <i class="fa fa-camera"></i>
              <input type="file" name="cover" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileCover();">
              </span>
              </span>
            </div>
            <input type="hidden" name="group_id" id="group-id" value="<?php echo $wo['group_profile']['id'];?>">
          </form>
          <?php } ?>
          <div class="user-cover-uploading-container"></div>
          <div class="user-cover-uploading-progress">
              <i class="fa fa-spinner fa-spin progress-icon" data-icon="spin"></i>
          </div>
          <img id="cover-image" src="<?php echo $wo['group_profile']['cover']?>" alt="<?php echo $wo['group_profile']['name']?> Cover Image"/>
        </div>
		
		<div class="media" id="grpwrpr" style="margin-top: 0px;background: #fff;width: 100%;height: 100%;position: relative;min-height: 110px;">
        <div class="media-left user-avatar flip" id="groupuserpic">
          <div class="user-avatar-uploading-container">
            <div class="user-avatar-uploading-progress" style="line-height: 90px;">
              <i class="fa fa-spinner fa-spin progress-icon" data-icon="spin"></i>
            </div>
          </div>
          <img id="group-avatar-image" alt="<?php echo $wo['group_profile']['name']?> Profile Picture" src="<?php echo $wo['group_profile']['avatar']?>"/>
          <?php if(Wo_IsGroupOnwer($wo['group_profile']['id']) === true) { ?>
          <form action="#" method="post" class="profile-avatar-changer">
            <div class="input-group">
              <span class="input-group-btn">
              <span class="btn btn-upload-image btn-file">
              <i class="fa fa-camera"></i>
              <input type="file" name="avatar" accept="image/x-png, image/jpeg" onchange="Wo_UpdateProfileAvatar();">
              </span>
              </span>
            </div>
            <input type="hidden" name="group_id" id="group-id" value="<?php echo $wo['group_profile']['id'];?>">
          </form>
          <?php } ?>
        </div>
        <div class="media-body title cusgrouptito" style="text-shadow: none;position: relative;width: auto;margin-top: 0px;">
            <span class="grpcatg" style="display: block;color: #666;font-size: 11px;"><?php echo $wo['group_profile']['category']; ?></span>
			<a class="grpttle" style="color: #222;font-size: 26px;" href="<?php echo Wo_SeoLink('index.php?link1=?link1=timeline&u=' . $wo['group_profile']['group_name'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>">
            <?php echo $wo['group_profile']['name']; ?>
            </a>
			<div class="grpmmbr" style="display: none;color: #989898;font-size: 11px;">
				<span><i class="zmdi zmdi-<?php echo $group_icon; ?>" style="margin: -1px 3px 0px 0px;"></i><?php echo $group_privacy; ?></span>
				<span style="margin: 0px 5px;"><i class="zmdi zmdi-circle" style="font-size: 4px;"></i></span>
				<span><?php echo Wo_CountGroupMembers($wo['group_profile']['id']);?> <?php echo $wo['lang']['members'];?></span>
			</div>
		</div>
		
		<div class="hdrmbrlist" style="text-align: center;margin-bottom: 20px;margin-top: 25px;display:none">
		<?php
            foreach (Wo_GetGroupMembers($wo['group_profile']['id']) as $wo['UsersList']) {
                echo Wo_LoadPage('group/follow-list');
            }
        ?>
		
		<?php if (Wo_CountGroupMembers($wo['group_profile']['id']) > 0) { ?>
		<?php if ($wo['loggedin'] == true) { ?>
		<?php if (Wo_IsGroupJoined($wo['group_profile']['id']) === true) { ?>
		<li class="list-group-item" style="display: inline-block;padding: 0;">
			<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=add_members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=add_members">
				<span class="zmdi-hc-stack zmdi-hc-lg">
					<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #ffffff;"></i>
					<i class="zmdi zmdi-plus-circle zmdi-hc-stack-1x" style="color: #03A9F4;font-size: 2em;"></i>
				</span>
			</a>
		</li>
		<?php } } } ?>
		</div>
		
		<div class="media-body options-buttons" id="grpoptns" style="bottom: 0px;margin-top: 0px;top: 40px;width: auto;">
            <span class="user-follow-button group-join-btn">
            <?php echo Wo_GetJoinButton($wo['group_profile']['id']);?>
			<?php if (Wo_IsGroupOnwer($wo['group_profile']['id'])) { ?>
			<a class="btn btn-default" href="<?php echo $wo['config']['site_url']; ?>/group-setting/<?php echo $wo['group_profile']['group_name'];?>" style="float: none;"><i class="zmdi zmdi-edit zmdi-hc-fw"></i><?php echo $wo['lang']['edit']; ?></a>
			<?php } ?>
			</span>
		</div>
		</div>
		
		<div id="profilenav" style="display: block;">
		<ul>
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=?link1=timeline&u=' . $wo['group_profile']['group_name'] . '');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>">Home</a></li>
		<li>
		<a class="groupmenulist" href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=members"><?php echo $wo['lang']['members'];?></a></li>
		</ul>
		</div>
		
      </div>
    </div>
  <div class="col-md-8">
             <?php
            if (isset($_GET['type'])) {
              if ($_GET['type'] == 'members') {
                if ($show_list == true) {
                  # code...
                
            ?>
        <div class="list-group profile-lists">
         <div class="list-group-item"><i class="fa fa-fw fa-users"></i> <?php echo $wo['lang']['members'];?></div>
            <div class="setting-well">
            <?php
               if (Wo_CountGroupMembers($wo['group_profile']['id']) == 0) {
                  echo '<h5 class="search-filter-center-text">' . $wo['lang']['no_members_found'] . '</h5>';
                } else {
                foreach (Wo_GetGroupMembers($wo['group_profile']['id']) as $wo['UsersList']) {
                  echo Wo_LoadPage('timeline/follow-list');
               }
              }
             ?>
            </div>
            <div class="clear"></div>
        </div>
    <?php } } else if ($_GET['type'] == 'add_members') {
      ?>
        <div class="list-group profile-lists">
         <div class="list-group-item"><i class="fa fa-fw fa-user-plus"></i> <?php echo $wo['lang']['add_your_frineds'];?></div>
            <div class="setting-well">
            <?php
               if (Wo_CountGroupsNotMember($wo['group_profile']['id']) == 0) {
                  echo '<h5 class="search-filter-center-text">' . $wo['lang']['added_all_friends'] . '</h5>';
                } else {
                foreach (Wo_GetGroupsNotMember($wo['group_profile']['id']) as $wo['UsersList']) {
                  echo Wo_LoadPage('group/add-list');
               }
              }
             ?>
            </div>
            <div class="clear"></div>
        </div>
     <?php } } else { ?>
    <?php echo Wo_GetGroupPostPublisherBox($wo['group_profile']['id']); ?>
    <?php if ($wo['loggedin'] == true) { echo Wo_LoadPage('story/filter-by'); } ?>
    <div id="posts" data-story-group="<?php echo $wo['group_profile']['id'];?>">
      <div class="pinned-post-container">
        <?php
          $pinedstory = Wo_GetPinnedPost($wo['group_profile']['id'], 'group');
          if (count($pinedstory) == 1) {
              foreach ($pinedstory  as $wo['story']) {
                echo Wo_LoadPage('story/content');
              }
          }
          ?>
      </div>
      <?php
        $stories = Wo_GetPosts(array('filter_by' => 'all', 'group_id' => $wo['group_profile']['id'])); 
        if (count($stories) == 0 && count($pinedstory) == 0) {
           echo Wo_LoadPage('story/group-no-stories');
        } else {
           foreach ($stories as $wo['story']) {
             echo Wo_LoadPage('story/content');
           }
        }
        ?>
    </div>
    <?php if ($wo['loggedin'] == true && count($stories) > 0) {  ?>
    <div class="load-more pointer" id="load-more-posts" onclick="Wo_GetMorePosts();">
      <span class="btn btn-default"><i class="fa fa-chevron-circle-down progress-icon" data-icon="chevron-circle-down"></i> <?php echo $wo['lang']['load_more_posts']; ?><span>
    </div>
    <?php
      }
      }
      ?>
    <div id="load-more-filter">
      <span class="filter-by-more hidden" data-filter-by="all"></span>
    </div>
  </div>
  <div class="col-md-4 cussidefix">
  
  <?php if($wo['loggedin'] == true) {  ?>
    <ul class="list-group" style="margin-bottom: -1px;border-bottom: 0px;border-bottom-left-radius: 0px;border-bottom-right-radius: 0px;">
      <li class="list-group-item text-muted search-for-posts-container" style="display:none"> 
      </li>
      <li class="list-group-item" style="padding: 10px;">
        <input type="text" class="form-control search-for-posts" placeholder="<?php echo $wo['lang']['search_for_posts']; ?>" onkeyup="Wo_SearchForPosts(this.value);" style="border-radius: 16px;">
      </li>
    </ul>
  <?php }?>
  
	<ul class="list-group pagesidebarlisttop">
		<?php 
      $group_privacy = $wo['lang']['public'];
      $group_icon = 'globe';
      if ($wo['group_profile']['privacy'] == 2) {
         $group_privacy = $wo['lang']['private'];
         $group_icon = 'lock';
      }
      ?>
       <?php if ($show_list == true): ?>
		<li class="list-group-item" style="background-color: #fff;border-bottom:0;  position: relative; display: block; padding: 5px 10px;font-size: 13px;background-color: #fff;color: #555">
			<span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #047cac;"></i>
				<i class="zmdi zmdi-accounts-alt zmdi-hc-stack-1x" style="color: white;"></i>
			</span>
			<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=members"><?php echo Wo_CountGroupMembers($wo['group_profile']['id']);?> <?php echo $wo['lang']['members'];?></a>
			<?php if (Wo_IsGroupOnwer($wo['group_profile']['id'])) { ?>
				<span class="green">+<?php echo Wo_CountJoinedThisWeek($wo['group_profile']['id']); ?> <?php echo $wo['lang']['this_week']; ?></span>
			<?php } ?>
		</li>
		<?php endif ?>
		<?php if ($wo['loggedin'] == true) { ?>
		<?php if (Wo_IsGroupJoined($wo['group_profile']['id']) === true) { ?>
		<li class="list-group-item">
			<span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f79f58;"></i>
				<i class="zmdi zmdi-plus-circle zmdi-hc-stack-1x" style="color: white;"></i>
			</span>
			<a href="<?php echo Wo_SeoLink('index.php?link1=timeline&u=' . $wo['group_profile']['group_name'] . '&type=add_members');?>" data-ajax="?link1=timeline&u=<?php echo $wo['group_profile']['group_name'];?>&type=add_members"><?php echo $wo['lang']['add_your_frineds']; ?></a>
		</li>
		<?php } } ?>
		<li class="list-group-item" <?php if ($show_list == false): ?>style="border-bottom: 0;position: relative;display: block;padding: 5px 10px;font-size: 13px;background-color: #fff;color: #555;"<?php endif ?>>
			<span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #6eceba;"></i>
				<i class="zmdi zmdi-<?php echo $group_icon; ?> zmdi-hc-stack-1x" style="color: white;"></i>
			</span>
			<?php echo $group_privacy; ?>
		</li>
		<li class="list-group-item">
			<span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f25e4e;"></i>
				<i class="zmdi zmdi-label zmdi-hc-stack-1x" style="color: white;"></i>
			</span>
			<?php echo $wo['group_profile']['category']; ?>
		</li>
		<li class="list-group-item">
			<span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #848688;"></i>
				<i class="zmdi zmdi-dns zmdi-hc-stack-1x" style="color: white;"></i>
			</span>
			<?php echo Wo_CountGroupPosts($wo['group_profile']['id']);?> <?php echo $wo['lang']['posts']; ?>
		</li>
		
		<?php if ($wo['loggedin'] && !Wo_IsAdmin() && $wo['user']['id'] != $wo['group_profile']['user_id'] && !Wo_IsAdmin($wo['group_profile']['user_id'])): ?>
        <?php if (!Wo_IsReportExists($wo['group_profile']['id'],'group')): ?>
        <li id="report_status" class="list-group-item pointer" onclick="$('#report_group').modal('show');">
            <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f79f58;"></i>
				<i class="zmdi zmdi-flag zmdi-hc-stack-1x" style="color: white;"></i>
			</span>
            <span>&nbsp;<?php echo $wo['lang']['report_group']; ?></span>
        </li>
        <?php else: ?>
        <li id="report_status" class="list-group-item pointer" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,false);">
            <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f79f58;"></i>
				<i class="zmdi zmdi-flag zmdi-hc-stack-1x" style="color: white;"></i>
			</span>
            <span>&nbsp;<?php echo $wo['lang']['unreport']; ?></span>
        </li>
        <?php endif; ?>
		<?php endif; ?>
    </ul>
    <?php if(!empty($wo['group_profile']['about'])) {  ?>
    <ul class="list-group">
		<li class="list-group-item text-muted" contenteditable="false"><i class="zmdi zmdi-info" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i> <?php echo $wo['lang']['about']; ?></li>
		<li class="list-group-item text-muted" contenteditable="false"><?php echo $wo['group_profile']['about']; ?></li>
    </ul>
    <?php } ?>
    <?php if($wo['loggedin'] == true) {  ?>
    
    <?php
      $groups = Wo_GroupSug(5);
      if (count($groups) > 0) {
      ?>
      <ul class="list-group" id="sidebar-group-list-container">
         <li class="list-group-item text-muted" contenteditable="false">
            <i class="zmdi zmdi-group-work" style="font-size: 20px;margin: -3px 5px 0px 0px;"></i> <?php echo $wo['lang']['suggested_groups'];?> <span onclick="Wo_ReloadSideBarGroups();" class="<?php echo Wo_RightToLeft('pull-right');?>  refresh">
            <i class="fa fa-repeat progress-icon" data-icon="repeat"></i>
            </span>
         </li>
         <div style="overflow: hidden;position: relative;width: 100%;">
                <div class="sidebar-groupz-may-know-container">
                    <?php 
                        foreach ($groups as $wo['GroupList']) {
                            $wo['GroupList']['name'] = mb_substr($wo['GroupList']['name'],0,20, "utf-8");
                            echo Wo_LoadPage('sidebar/sidebar-group-list');
                        } 
                        ?>
                </div>
				<span class="user-navigate scrollRight"><a id="scrollRight" href="javascript:;"><i class="zmdi zmdi-chevron-left bold"></i></a></span>
				<span class="user-navigate scrollLeft"><a id="scrollLeft" href="javascript:;"><i class="zmdi zmdi-chevron-right bold"></i></a></span>
			</div>
         <div class="clear"></div>
      </ul>
      <?php } ?>
    <?php } ?>
    <?php 
      $sidebar_ad = Wo_GetAd('sidebar', false);
      if (!empty($sidebar_ad)) {?>
    <ul class="list-group sidebar-ad">
      <?php echo $sidebar_ad; ?>
    </ul>
    <?php } ?>
  </div>
</div>

<div class="modal fade matdialog" id="report_group" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <h4 class="modal-title"><?php echo $wo['lang']['report_group']; ?></h4>
         </div>
         <div class="modal-body" style="overflow: visible;">
            <textarea class="form-control" placeholder="Type text" dir="auto" rows="5" id="report-group-text-<?php echo $wo['group_profile']['id']; ?>" autofocus></textarea>
         </div>
         <div class="modal-footer">
			<button type="button" class="btn matbtn wabe btn-default" data-dismiss="modal"><?php echo $wo['lang']['cancel']; ?></button>
            <button type="button" class="btn matbtn wabe btn-main" id="report-group-button" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,true)" >
            <?php echo $wo['lang']['send']; ?></button>
         </div>
      </div>
   </div>
</div>
<style>
body {padding-left: 0px;}
.navbar-default {padding-right: 0px;}

@media (min-width: 1200px){
body {padding-left: 0px;padding-right: 205px;}
.navbar-default {padding-right: 205px;}
}
@media (min-width: 1500px){
body {padding-left: 0px;padding-right: 260px;}
}
@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
}
</style>
<?php if($wo['loggedin'] == false) {  ?>
<style>
body {padding-left: 0px;}
.navbar-default {padding-right: 0px;}
@media (min-width: 1200px){
body {padding-left: 0px;padding-right: 0px;}
.navbar-default {padding-right: 0px;}
}
@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
.hideinmenu {display: none;}
}
</style>
<?php } ?>
<!-- JS Pages functions -->
<script>
$(function () {
  if($(window).width() > 600) {
    $(".user-avatar").hover(function () {
      $('.profile-avatar-changer').fadeIn(100);
    }, function () {
      $('.profile-avatar-changer').fadeOut(100);
    });
  }
  if($(window).width() > 600) {
    $(".user-cover").hover(function () {
      $('.profile-cover-changer').fadeIn(100);
    }, function () {
      $('.profile-cover-changer').fadeOut(100);
    });
  }
  $('form.profile-avatar-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_group_avatar_picture',

    beforeSend: function () {
      $('.user-avatar-uploading-container,.user-avatar-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      if(data.status == 200) {
        $('[id^=group-avatar-image]').attr("src", data.img);
      }
      $('.user-avatar-uploading-container, .user-avatar-uploading-progress').fadeOut(200);
    }
  });

  $('form.profile-cover-changer').ajaxForm({
    url: Wo_Ajax_Requests_File() + '?f=update_group_cover_picture',

    beforeSend: function () {
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeIn(200);
    },
    success: function (data) {
      if(data.status == 200) {
        $('[id^=cover-image]').attr("src", data.img);
      }
      $('.user-cover-uploading-container,.user-cover-uploading-progress').fadeOut(200);
    }
  });
});

function Wo_UpdateProfileAvatar() {
  $("form.profile-avatar-changer").submit();
}

function Wo_UpdateProfileCover() {
  $("form.profile-cover-changer").submit();
}

function Wo_ReportGroup(id = false,report = true){
    var report_text = $("#report-group-text-<?php echo $wo['group_profile']['id']; ?>").val();
    if (!id) {return false;}
    else if(report == true){
      if (!report_text) {return false;}  
    }
    Wo_progressIconLoader($("#report-group-button"));
    $.ajax({
        url: Wo_Ajax_Requests_File() + '?f=reports&s=report_group',
        type: 'POST',
        dataType: 'json',
        data: {text:report_text,group:id}
    })
    .done(function(data) {
        if(data.status == 200 && data.code == 0){
            $('#report_status').replaceWith('\
                <li id="report_status" class="list-group-item pointer" onclick="$(\'#report_group\').modal(\'show\');">\
            <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">\
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f79f58;"></i>\
				<i class="zmdi zmdi-flag zmdi-hc-stack-1x" style="color: white;"></i>\
			</span>\
            <span>&nbsp;<?php echo $wo['lang']['report_group']; ?></span>\
        </li>');
		Snackbar.show({text: '<?php echo $wo['group_profile']['name']; ?> has been unreported successfully.'});
        }

        else if (data.status == 200 && data.code == 1) {
            $("#report-group-text-<?php echo $wo['group_profile']['id']; ?>").val('');
            $("#report_group").modal('hide');
            $('#report_status').replaceWith('\
                <li id="report_status" class="list-group-item pointer" onclick="Wo_ReportGroup(<?php echo $wo['group_profile']['id']; ?>,false);">\
            <span class="zmdi-hc-stack zmdi-hc-lg" style="margin-right: 6px;">\
				<i class="zmdi zmdi-circle zmdi-hc-stack-2x" style="color: #f79f58;"></i>\
				<i class="zmdi zmdi-flag zmdi-hc-stack-1x" style="color: white;"></i>\
			</span>\
            <span>&nbsp;<?php echo $wo['lang']['unreport']; ?></span>\
        </li>');
		Snackbar.show({text: '<?php echo $wo['group_profile']['name']; ?> has been reported successfully.'});
        }
        Wo_progressIconLoader($("#report-group-button"));
        
    })
    .fail(function() {
        console.log("error");
    })
}

$(function(){

    var url = window.location.pathname, 
        urlRegExp = new RegExp(url.replace(/\/$/,'') + "$"); // create regexp to match current url pathname and remove trailing slash if present as it could collide with the link in navigation in case trailing slash wasn't present there
        // now grab every link from the navigation
        $('#profilenav a').each(function(){
            // and test its normalized href against the url pathname regexp
            if(urlRegExp.test(this.href.replace(/\/$/,''))){
                $(this).addClass('menuactive');
            }
        });

});
</script>