<?php echo Wo_LoadPage('ads/includes/header'); ?>
<div class="send-money-container">
  <br>
  <br>
  <div class="col-md-8"> 

    <form class="form" id="send-money-form" autocomplete="off">
      <div class="col-md-12" id="send-money-form-alert">
      <?php if ($wo['user']['wallet'] == '0.00' || $wo['user']['wallet'] == '0'): ?>
          <div class="alert alert-warning">
            <?php echo $wo['lang']['balance_is_0'] ?> 
            <span>
              <i class="fa fa-university" aria-hidden="true"></i>
            </span>
            <a href="<?php echo Wo_SeoLink('index.php?link1=wallet'); ?>">      
              <?php echo $wo['lang']['top_up'] ?>
            </a>
          </div>
      <?php else: ?>  
        <div class="alert alert-info"> 
          <p>
            <i class="fa fa-info-circle"></i> <?php echo $wo['lang']['u_send_money']; ?>
          </p>
        </div>
      <?php endif; ?>
      </div>
    	<div class="form-group">
    		<label class="col-md-3">
          <?php echo $wo['lang']['available_balance']; ?>  
        </label>
	  		<div class="col-md-9">
          <h5>
            <b> <?php echo sprintf('%.2f',$wo['user']['wallet']);?><?php echo Wo_GetCurrency($wo['config']['ads_currency']); ?></b>
          </h5>
	  		</div>
	  		<div class="clear"></div>
    	</div>
    	<div class="form-group">
    		<label class="col-md-3"><?php echo $wo['lang']['send_to']; ?></label>
	  		<div class="col-md-9">
	  			<input id="search" type="text" placeholder="<?php echo $wo['lang']['search_name_or_email']; ?>" class="form-control">
          <div class="dropdown">
            <ul class="dropdown-menu money-recipients-list">

            </ul>
          </div>
	  		</div>
	  		<div class="clear"></div>
    	</div>

    	<div class="form-group w100 add-amount">
    		<label class="col-md-3">
          <?php echo $wo['lang']['amount'];?>
        </label>
    		<div class="col-md-9">
    			<input step="any" type="number" class="form-control" placeholder="0.00" min="1.00" max="1000"  name="amount" id="amount">
    		</div>
    	</div>
    	<div class="form-group w100">
    		<label class="col-md-3"></label>
    		<div class="col-md-9">
    			<button type="submit" class="btn btn-main" <?php echo ($wo['user']['wallet'] == '0.00' || $wo['user']['wallet'] == '0') ? 'disabled' : ''; ?>>
            <i class="fa fa-paper-plane progress-icon" data-icon="paper-plane"></i>&nbsp;
    				<?php echo $wo['lang']['continue'];?>
    			</button>
    		</div>
    	</div>
      <input type="hidden" id="recipient_user_id" name="user_id">
    </form>
  </div> 
  <div class="clear"></div>
</div>

<script>
  jQuery(document).ready(function($) {
    $("#send-money-form").find('#search').keydown(function(event) {
      let name = $(this).val();
      $.ajax({
        url: Wo_Ajax_Requests_File(),
        type: 'GET',
        dataType: 'json',
        data: {f: 'family',s:'search',name:name},
      })
      .done(function(data) {
        if (data.status == 200) {
          $("#send-money-form").find(".dropdown").addClass('open').find('ul').empty();
          for (var i = 0; i < data.users.length; i++) {
            $("<li>",{
              class:"pointer",
              id: data.users[i].user_id,
              text: data.users[i].name
            }).appendTo('ul.money-recipients-list');     
          }
        }
        else{
          $("#send-money-form").find(".dropdown").removeClass('open').find('ul').empty();
        }
      });
    });


    $(document).on('click', 'ul.money-recipients-list li', function(event) {
      event.preventDefault();
      $("#recipient_user_id").val($(this).attr('id'));
      $("#send-money-form").find('#search').val($(this).text());
      $("#send-money-form").find(".dropdown").removeClass('open').find('ul').empty();
    });

    $("#send-money-form").ajaxForm({
      url: Wo_Ajax_Requests_File() + '?f=wallet&s=send',
      type:"POST",
      beforeSend: function() {
        Wo_progressIconLoader($("#send-money-form").find('button.btn-main'));
      },
      success: function(data) {
        scrollToTop();
        if (data['status'] == 200) {
          var alert_msg = $("<div>",{
            class: "alert alert-success",
            text: data['message']
          }).prepend('<i class="fa fa-info-check-o"></i> ');;

          $("#send-money-form-alert").html(alert_msg);
          $("#send-money-form").resetForm();
        } 

        else if (data['message']) {
          var alert_msg = $("<div>",{
            class: "alert alert-danger",
            text: (data['message'])
          }).prepend('<i class="fa fa-info-circle"></i> ');

          $("#send-money-form-alert").html(alert_msg);
        } 

        Wo_progressIconLoader($("#send-money-form").find('button.btn-main'));
      }
    });

  });
</script>
