<div class="page-margin">
   <div class="row">
   <div class="col-md-2 offnavmenu"><?php echo Wo_LoadPage("sidebar/left-sidebar"); ?></div>
      <div class="col-md-7 cushomewider" style="padding-left: 0px;padding-right: 0px;">
         <div class="list-group red-list">
            <div class="list-group-item"><i class="zmdi zmdi-email" style="font-size: 18px;margin: -4px 5px 0px 0px;"></i> <?php echo $wo['lang']['contact_us']; ?></div>
            <div class="setting-well">
               <form class="contact-us-form form-horizontal" method="post">
                  <fieldset>
                     <div class="contact-us-alert setting-update-alert"></div>
                     <!-- Text input-->
                     <div class="form-group">
                        <label class="col-md-3" for="first_name"><?php echo $wo['lang']['first_name'];?> *</label>  
                        <div class="col-md-6">
                           <input id="first_name" name="first_name" type="text" class="form-control input-md">
                        </div>
                     </div>
                     <!-- Text input-->
                     <div class="form-group">
                        <label class="col-md-3" for="last_name"><?php echo $wo['lang']['last_name'];?> *</label>  
                        <div class="col-md-6">
                           <input id="last_name" name="last_name" type="text" class="form-control input-md">
                        </div>
                     </div>
                     <div class="form-group">
                        <label class="col-md-3" for="email"><?php echo $wo['lang']['email'];?> *</label>  
                        <div class="col-md-6">
                           <input name="email" id="email" type="text" class="form-control input-md">
                        </div>
                     </div>
                     <div class="form-group">
                        <label class="col-md-3" for="message"><?php echo $wo['lang']['message'];?> *</label>  
                        <div class="col-md-6">
                           <textarea name="message" id="message" rows="5" class="form-control input-md"></textarea>
                        </div>
                     </div>
                     <hr>
                     <div class="form-group last-btn">
                        <label class="col-md-3"></label>
                        <div class="col-sm-3 text-left">
                           <button type="submit" name="send" id="send" tabindex="4" class="wabe mdbtn btn btn-main">
                           <i class="fa fa-paper-plane-o progress-icon" data-icon="paper-plane-o"></i> <?php echo $wo['lang']['send'];?>
                           </button>
                        </div>
                     </div>
                  </fieldset>
               </form>
            </div>
         </div>
      </div>
      <!-- .col-md-8 -->
	  <div class="col-md-3 cushomesmaller">
      <?php
         if ($wo['loggedin'] == true) {
          echo Wo_LoadPage('sidebar/content');
         } else {
          echo Wo_LoadPage('sidebar/guest');
         }
         ?>
		 </div>
   </div>
   <!-- .row -->
</div>
<!-- .page-margin -->

<?php if($wo['loggedin'] == false) {  ?>
<style>
body {padding-left: 150px;}
.navbar-default {padding-right: 0px;}
.offnavmenu{display:none}
@media (min-width: 1200px){
body {padding-left: 170px;padding-right: 0px;}
.navbar-default {padding-right: 0px;}
}
@media (min-width: 1500px){
body {padding-left: 200px;padding-right: 0px;}
}
@media (max-width: 990px) {
body {padding-left: 0px;overflow-x: auto;}
.hideinmenu {display: none;}
}
</style>
<?php } ?>
<script>
   $(function() {
     $('form.contact-us-form').ajaxForm({
       url: Wo_Ajax_Requests_File() + '?f=contact_us',
       beforeSend: function() {
         Wo_progressIconLoader($('form.contact-us-form').find('button'));
       },
       success: function(data) {
         if (data.status == 200) {
            $('.contact-us-alert').html('<div class="alert alert-success">' + data.message + '</div>');
			$('form.contact-us-form')[0].reset();
            $('.alert-success').fadeIn(300);
         } else {
             var errors = data.errors.join("<br>");
             $('.contact-us-alert').html('<div class="alert alert-danger">' + errors + '</div>');
             $('.alert-danger').fadeIn(300);
         }
         Wo_progressIconLoader($('form.contact-us-form').find('button'));
       }
     });
   });
</script>